--- #YAML:1.0
name: OpenGuides
version: 0.31
license: perl
distribution_type: module
requires:
  Algorithm::Diff: 0.13
  CGI: 2.42
  CGI::Carp: 0
  CGI::Cookie: 0
  CGI::Wiki: 0.49
  CGI::Wiki::Formatter::UseMod: 0.09
  CGI::Wiki::Plugin::Categoriser: 0
  CGI::Wiki::Plugin::Diff: 0
  CGI::Wiki::Plugin::GeoCache: 0
  CGI::Wiki::Plugin::Locator::UK: 0.06
  CGI::Wiki::Plugin::RSS::ModWiki: 0.02
  Config::Tiny: 0
  DBD::Pg: 0
  Data::Dumper: 0
  File::Spec::Functions: 0
  Geography::NationalGrid: 0
  Parse::RecDescent: 0
  Search::InvertedIndex: 0
  Template: 0
  Test::MockObject: 0.07
  Time::Piece: 0
  URI::Escape: 0
recommends: {}
build_requires:
  Module::Build: 0.18
conflicts: {}
dynamic_config: 1
provides:
  OpenGuides:
    file: lib/OpenGuides.pm
    version: 0.31
  OpenGuides::Build:
    file: lib/OpenGuides/Build.pm
  OpenGuides::CGI:
    file: lib/OpenGuides/CGI.pm
    version: 0.04
  OpenGuides::Diff:
    file: lib/OpenGuides/Diff.pm
    version: 0.04
  OpenGuides::RDF:
    file: lib/OpenGuides/RDF.pm
    version: 0.06
  OpenGuides::SuperSearch:
    file: lib/OpenGuides/SuperSearch.pm
    version: 0.04
  OpenGuides::Template:
    file: lib/OpenGuides/Template.pm
    version: 0.12
  OpenGuides::UK::PubCrawl:
    file: lib/OpenGuides/UK/PubCrawl.pm
    version: 0.02
  OpenGuides::Utils:
    file: lib/OpenGuides/Utils.pm
    version: 0.06
generated_by: Module::Build version 0.20
