--- #YAML:1.0
name: OpenGuides
version: 0.48
author: ~
abstract: ~
license: perl
requires:
  Algorithm::Diff: 0.13
  CGI: 2.92
  CGI::Carp: 0
  CGI::Cookie: 0
  CGI::Wiki: 0.62
  CGI::Wiki::Formatter::UseMod: 0.16
  CGI::Wiki::Plugin::Categoriser: 0
  CGI::Wiki::Plugin::Diff: 0.07
  CGI::Wiki::Plugin::Locator::Grid: 0.02
  CGI::Wiki::Plugin::RSS::ModWiki: 0.072
  CGI::Wiki::Plugin::RSS::Reader: 1.3
  Class::Accessor: 0
  Config::Tiny: 0
  DBD::Pg: 0
  Data::Dumper: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Geography::NationalGrid: 0
  LWP::Simple: 0
  Parse::RecDescent: 0
  Plucene: 0
  Template: 0
  Test::MockObject: 0.07
  Time::Piece: 0
  URI::Escape: 0
  XML::RSS: 0
recommends:
  DBD::SQLite: 0
  Test::HTML::Content: 0
build_requires:
  Module::Build: 0.18
dynamic_config: 1
provides:
  OpenGuides:
    file: lib/OpenGuides.pm
    version: 0.48
  OpenGuides::Build:
    file: lib/OpenGuides/Build.pm
  OpenGuides::CGI:
    file: lib/OpenGuides/CGI.pm
    version: 0.06
  OpenGuides::Config:
    file: lib/OpenGuides/Config.pm
  OpenGuides::RDF:
    file: lib/OpenGuides/RDF.pm
    version: 0.07
  OpenGuides::SuperSearch:
    file: lib/OpenGuides/SuperSearch.pm
    version: 0.09
  OpenGuides::Template:
    file: lib/OpenGuides/Template.pm
    version: 0.12
  OpenGuides::Test:
    file: lib/OpenGuides/Test.pm
    version: 0.02
  OpenGuides::Utils:
    file: lib/OpenGuides/Utils.pm
    version: 0.08
generated_by: Module::Build version 0.25
