name: CI
env:
    AUTOMATED_TESTING: 1
on:
  - push
  - pull_request

jobs:
  perl_tester:
    runs-on: ubuntu-latest
    name: "perl ${{ matrix.perl_version }}"

    strategy:
      fail-fast: false
      matrix:
        # versions of perl shipped with ubuntu/debian and latest
        perl_version:
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"

    container:
      image: "perldocker/perl-tester:${{ matrix.perl_version }}"

    steps:
      - uses: actions/checkout@v2
        # install modules needed to make full test suite run
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          install: |
            Config::Tiny
            Geo::HelmertTransform
            Test::HTML::Content
            Wiki::Toolkit::Plugin::Ping
            Devel::Cover::Report::Coveralls
            Test::JSON
            Class::Accessor
            Lucy
          sudo: false
          args: "--quiet"
        # install default module dependences
      - run: cpanm --quiet --installdeps --notest .
      - run: perl Build.PL
      - run: ./Build build
        # actually run the tests
      - run: ./Build test
